"""Rebuild every phase00 fixture's units from its committed IR and compare.

The committed document_units.v1.jsonl files ARE the determinism baseline; this
test closes the round8 audit blocker that they were regenerated by hand but
never verified against the current rule bundle in CI.
"""

from __future__ import annotations

import json
from pathlib import Path
import unittest

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "phase00"


class FixtureDeterminismTests(unittest.TestCase):
    def test_committed_units_match_current_rules_rebuild(self) -> None:
        import scripts.regen_phase00_fixtures as regen

        sample_dirs = [
            item
            for item in sorted(FIXTURES.iterdir())
            if (item / "document_units.v1.jsonl").exists()
        ]
        self.assertTrue(sample_dirs, "no phase00 fixtures found")
        for sample_dir in sample_dirs:
            with self.subTest(sample=sample_dir.name):
                committed = (sample_dir / "document_units.v1.jsonl").read_text(
                    encoding="utf-8"
                )
                ir = json.loads(
                    (sample_dir / "normalized_ir.v2.json").read_text(encoding="utf-8")
                )
                rebuilt = regen.render_document_units_jsonl(
                    normalized_ir=ir, sample_key=sample_dir.name
                )
                self.assertEqual(
                    rebuilt,
                    committed,
                    f"{sample_dir.name}: committed fixture drifted from the "
                    "current rule bundle — run scripts/regen_phase00_fixtures.py "
                    f"--units-only {sample_dir.name} and review the diff",
                )


if __name__ == "__main__":
    unittest.main()
