index_pool:
  table_name: "stk_pool_of_index"
  pool_codes:
    - "000300.SH"  # 沪深300
    - "000905.SH"  # 中证500
    - "000852.SH"  # 中证1000
    # - "000906.SH"  # 中证800
    # - "000016.SH"  # 上证50
  init_start_date: "20050104"
  overlap_days: 20
  calendar_market: "SSE"
  write_batch_rows: 200000
