<#
.SYNOPSIS
Independent M6 native owner component suite runner (Windows PowerShell 5.1).

.DESCRIPTION
1. Fingerprints the compiler and the 12 production C# sources.
2. Compiles the 12 production sources ALONE into the fixed owner executable
   (csc.exe /noconfig /warnaserror+ /main:MineruM6OwnerHost) to prove they
   build without test code, then compiles 4 test sources referencing that executable into
   the suite executable (/main:MineruM6NativeSuite).
3. Runs the suite against the Python-generated wire vectors under a fresh
   disposable output root, then runs the finite self-Job child scenarios as
   real child processes held by exact PID/creation time.
4. Writes runner-evidence.json and leaves every artifact in place on failure.

Never touches C:\ProgramData, Docker, GPU business work, firewall, SSH or
service configuration. Requires no network. The identity test reads the
machine registry read-only; it does not load NVML.

.PARAMETER SourceRoot
Directory holding the production and test .cs files (default: this script's
directory, i.e. scripts/windows in the repository).

.PARAMETER FixturePath
wire-vectors.v2.json generated by tests/fixtures/m6_owner/generate_m6_owner_fixtures.py.
Default: <SourceRoot>\..\..\tests\fixtures\m6_owner\wire-vectors.v2.json.

.PARAMETER OutputRoot
Fresh disposable root (default: %TEMP%\m6-native-suite-<utc timestamp>). Must not
be under C:\ProgramData.

.EXAMPLE
powershell.exe -NoProfile -ExecutionPolicy RemoteSigned -File .\scripts\windows\test_mineru_m6_native_suite.ps1
#>
[CmdletBinding()]
param(
    [string]$SourceRoot = $PSScriptRoot,
    [string]$FixturePath = "",
    [string]$OutputRoot = "",
    [ValidateRange(1, 1800)][int]$SuiteTimeoutSeconds = 300,
    [ValidateRange(1, 30)][int]$SelfJobExpirySeconds = 3,
    [switch]$SkipSelfJobChildren
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version 2

# ---------------------------------------------------------------------------
# Preconditions and safety bounds
# ---------------------------------------------------------------------------
if ($PSVersionTable.PSVersion.Major -ne 5) { throw "Windows PowerShell 5.1 is required; running $($PSVersionTable.PSVersion)" }
if (-not [Environment]::Is64BitProcess) { throw "64-bit PowerShell is required (self-Job, QPC and NVML paths are 64-bit only)" }

$ProductionSources = @(
    "mineru_m6_owner_binding.cs", "mineru_m6_owner_endpoint.cs", "mineru_m6_owner_host.cs",
    "mineru_m6_owner_identity.cs", "mineru_m6_owner_journal.cs", "mineru_m6_owner_platform.cs",
    "mineru_m6_owner_wire.cs", "mineru_m6_private_store.cs", "mineru_m6_run_control.cs",
    "mineru_m6_writer_guard.cs", "mineru_nvml_backend.cs", "mineru_resident_wire.cs"
)
$TestSources = @(
    "test_mineru_m6_native_suite.cs", "test_mineru_m6_native_journal_store.cs",
    "test_mineru_m6_native_endpoint_control.cs", "test_mineru_m6_native_identity_job.cs"
)
$SourceRoot = [IO.Path]::GetFullPath($SourceRoot)
if ([string]::IsNullOrEmpty($FixturePath)) {
    $FixturePath = Join-Path $SourceRoot "..\..\tests\fixtures\m6_owner\wire-vectors.v2.json"
}
$FixturePath = [IO.Path]::GetFullPath($FixturePath)
if ([string]::IsNullOrEmpty($OutputRoot)) {
    $OutputRoot = Join-Path ([IO.Path]::GetTempPath()) ("m6-native-suite-" + (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ") + "-" + [Guid]::NewGuid().ToString("N").Substring(0, 6))
}
$OutputRoot = [IO.Path]::GetFullPath($OutputRoot)
foreach ($forbidden in @("C:\ProgramData", "C:\Windows", "C:\Program Files")) {
    if ($OutputRoot.StartsWith($forbidden, [StringComparison]::OrdinalIgnoreCase)) { throw "output root must be a disposable location, not $forbidden" }
}
if (Test-Path -LiteralPath $OutputRoot) { throw "output root must be fresh: $OutputRoot" }
foreach ($name in ($ProductionSources + $TestSources)) {
    if (-not (Test-Path -LiteralPath (Join-Path $SourceRoot $name) -PathType Leaf)) { throw "missing source: $name under $SourceRoot" }
}
if (-not (Test-Path -LiteralPath $FixturePath -PathType Leaf)) {
    throw "fixture missing: $FixturePath (generate it with tests/fixtures/m6_owner/generate_m6_owner_fixtures.py)"
}
$FrameworkDir = Join-Path (Split-Path -Parent ([Environment]::SystemDirectory)) "Microsoft.NET\Framework64\v4.0.30319"
$Csc = Join-Path $FrameworkDir "csc.exe"
if (-not (Test-Path -LiteralPath $Csc -PathType Leaf)) { throw "compiler missing: $Csc" }

New-Item -ItemType Directory -Path $OutputRoot | Out-Null
$BuildDir = Join-Path $OutputRoot "build"
$WorkDir = Join-Path $OutputRoot "work"
New-Item -ItemType Directory -Path $BuildDir, $WorkDir | Out-Null

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Get-Sha256File {
    param([Parameter(Mandatory = $true)][string]$Path)
    return "sha256:" + (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()
}

function ConvertTo-CommandLineArgument {
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Value)
    if ($Value.Length -gt 0 -and $Value -notmatch '[\s"]') { return $Value }
    $builder = New-Object Text.StringBuilder
    [void]$builder.Append('"')
    $backslashes = 0
    foreach ($character in $Value.ToCharArray()) {
        if ($character -eq '\') { $backslashes++; continue }
        if ($character -eq '"') { [void]$builder.Append('\' * ($backslashes * 2 + 1)); [void]$builder.Append('"'); $backslashes = 0; continue }
        if ($backslashes -gt 0) { [void]$builder.Append('\' * $backslashes); $backslashes = 0 }
        [void]$builder.Append($character)
    }
    if ($backslashes -gt 0) { [void]$builder.Append('\' * ($backslashes * 2)) }
    [void]$builder.Append('"')
    return $builder.ToString()
}

# Build the independent suspended launcher in this PowerShell process. No
# production code is included in this helper. Each invocation gets an unnamed
# finite-memory Job BEFORE its suspended primary thread can run; output goes
# directly to fresh files so inherited stdout can never block a pipe drain.
Add-Type -Path (Join-Path $SourceRoot "test_mineru_m6_process.cs") -ErrorAction Stop
$script:InvocationNumber = 0
function Invoke-Native {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [Parameter(Mandatory = $true)][AllowEmptyCollection()][string[]]$Arguments,
        [ValidateRange(1, 1800)][int]$TimeoutSeconds = 300,
        [string]$WorkingDirectory = $WorkDir
    )
    $script:InvocationNumber++
    $prefix = Join-Path $OutputRoot ("process-" + $script:InvocationNumber)
    $process = New-Object M6BoundedProcess($FilePath, $Arguments, $WorkingDirectory, $prefix)
    try {
        $process.Finish($TimeoutSeconds * 1000)
        return [pscustomobject]@{
            file_path = $FilePath; arguments = $Arguments; pid = $process.Pid
            creation_filetime_100ns = $process.CreationFiletime; exit_code = $process.ExitCode
            elapsed_ms = $process.ElapsedMilliseconds; timed_out = $process.TimedOut
            exact_process_exited = $process.ExactProcessExited
            active_job_processes = $process.ActiveJobProcesses; total_job_processes = $process.TotalJobProcesses
            forced_termination = $process.ForcedTermination; cleanup_failure = $process.CleanupFailure
            stdout = $process.ReadStdout(); stderr = $process.ReadStderr()
        }
    }
    catch {
        [IO.File]::WriteAllText($prefix + ".runner-error.txt", ($_ | Out-String))
        throw
    }
    finally { $process.Dispose() }
}

function Write-Utf8 {
    param([string]$Path, [string]$Text)
    [IO.File]::WriteAllText($Path, $Text, (New-Object Text.UTF8Encoding($false)))
}

$Failures = New-Object Collections.ArrayList
function Add-Failure { param([string]$Text) [void]$Failures.Add($Text); Write-Host "FAIL: $Text" -ForegroundColor Red }
function Assert-True { param([bool]$Condition, [string]$What) if ($Condition) { Write-Host "ok: $What" } else { Add-Failure $What } }

# ---------------------------------------------------------------------------
# Fingerprints
# ---------------------------------------------------------------------------
$Evidence = [ordered]@{
    contract_version = "m6.native-suite-runner-evidence.v1"
    started_utc = (Get-Date).ToUniversalTime().ToString("o")
    powershell_version = $PSVersionTable.PSVersion.ToString()
    clr_version = [Environment]::Version.ToString()
    machine_qpc_frequency_hz = [Diagnostics.Stopwatch]::Frequency
    compiler_path = $Csc
    compiler_sha256 = (Get-Sha256File -Path $Csc)
    source_root = $SourceRoot
    output_root = $OutputRoot
    fixture_path = $FixturePath
    fixture_sha256 = (Get-Sha256File -Path $FixturePath)
    production_sources = [ordered]@{}
    test_sources = [ordered]@{}
}
foreach ($name in $ProductionSources) { $Evidence.production_sources[$name] = Get-Sha256File -Path (Join-Path $SourceRoot $name) }
foreach ($name in ($TestSources + @("test_mineru_m6_process.cs", "test_mineru_m6_native_suite.ps1"))) { $Evidence.test_sources[$name] = Get-Sha256File -Path (Join-Path $SourceRoot $name) }
$manifestText = ($ProductionSources | ForEach-Object { $_ + " " + $Evidence.production_sources[$_] }) -join "`n"
$Evidence["production_source_manifest_sha256"] = "sha256:" + ((-join ([Security.Cryptography.SHA256]::Create().ComputeHash([Text.Encoding]::UTF8.GetBytes($manifestText + "`n")) | ForEach-Object { $_.ToString("x2") })))

# ---------------------------------------------------------------------------
# Compile: production alone, then tests referencing its public API
# ---------------------------------------------------------------------------
$CommonCscArguments = @(
    "/noconfig", "/nologo", "/warnaserror+", "/nowarn:1701,1702", "/target:exe", "/platform:x64",
    "/optimize-", "/debug-", "/lib:$FrameworkDir",
    "/r:System.dll", "/r:System.Core.dll", "/r:System.Management.dll", "/r:System.Net.Http.dll", "/r:System.IO.Compression.dll"
)
$HostExe = Join-Path $BuildDir "mineru_m6_owner_host.exe"
$SuiteExe = Join-Path $BuildDir "m6_native_suite.exe"
$productionPaths = @($ProductionSources | ForEach-Object { Join-Path $SourceRoot $_ })
$testPaths = @($TestSources | ForEach-Object { Join-Path $SourceRoot $_ })

Write-Host "compiling production sources alone -> $HostExe"
$hostBuild = Invoke-Native -FilePath $Csc -Arguments (@($CommonCscArguments) + @("/main:MineruM6OwnerHost", "/out:$HostExe") + $productionPaths) -TimeoutSeconds 300
$Evidence["production_build"] = [ordered]@{ command = ($hostBuild.arguments -join " "); exit_code = $hostBuild.exit_code; stdout = $hostBuild.stdout; stderr = $hostBuild.stderr }
Assert-True ($hostBuild.exit_code -eq 0 -and (Test-Path -LiteralPath $HostExe)) "production sources compile alone with /noconfig /warnaserror+"
if ($hostBuild.exit_code -ne 0) { Write-Host $hostBuild.stdout; Write-Host $hostBuild.stderr }
if (Test-Path -LiteralPath $HostExe) { $Evidence["production_exe_sha256"] = Get-Sha256File -Path $HostExe }

Write-Host "compiling suite -> $SuiteExe"
$suiteBuild = Invoke-Native -FilePath $Csc -Arguments (@($CommonCscArguments) + @("/main:MineruM6NativeSuite", "/out:$SuiteExe", "/r:$HostExe") + $testPaths) -TimeoutSeconds 300
$Evidence["suite_build"] = [ordered]@{ command = ($suiteBuild.arguments -join " "); exit_code = $suiteBuild.exit_code; stdout = $suiteBuild.stdout; stderr = $suiteBuild.stderr }
Assert-True ($suiteBuild.exit_code -eq 0 -and (Test-Path -LiteralPath $SuiteExe)) "suite compiles with /noconfig /warnaserror+"
if ($suiteBuild.exit_code -ne 0) { Write-Host $suiteBuild.stdout; Write-Host $suiteBuild.stderr }

# ---------------------------------------------------------------------------
# Run the component suite
# ---------------------------------------------------------------------------
$SuiteEvidencePath = Join-Path $OutputRoot "suite-evidence.json"
if (Test-Path -LiteralPath $SuiteExe) {
    $Evidence["suite_exe_sha256"] = Get-Sha256File -Path $SuiteExe
    Write-Host "running component suite"
    $suiteRun = Invoke-Native -FilePath $SuiteExe -Arguments @($FixturePath, $SuiteEvidencePath, $WorkDir) -TimeoutSeconds $SuiteTimeoutSeconds
    Write-Utf8 -Path (Join-Path $OutputRoot "suite-stdout.txt") -Text $suiteRun.stdout
    Write-Utf8 -Path (Join-Path $OutputRoot "suite-stderr.txt") -Text $suiteRun.stderr
    $Evidence["suite_run"] = [ordered]@{
        pid = $suiteRun.pid; creation_filetime_100ns = $suiteRun.creation_filetime_100ns; exit_code = $suiteRun.exit_code
        active_job_processes = $suiteRun.active_job_processes; total_job_processes = $suiteRun.total_job_processes; cleanup_failure = $suiteRun.cleanup_failure; forced_termination = $suiteRun.forced_termination
        elapsed_ms = $suiteRun.elapsed_ms; timed_out = $suiteRun.timed_out; exact_process_exited = $suiteRun.exact_process_exited
        stdout_tail = ($suiteRun.stdout -split "`n" | Select-Object -Last 40) -join "`n"
        stderr = $suiteRun.stderr
    }
    Assert-True (-not $suiteRun.timed_out) "suite finished within $SuiteTimeoutSeconds s"
    Assert-True ($suiteRun.exact_process_exited) "suite process exited (exact PID/creation identity)"
    if (Test-Path -LiteralPath $SuiteEvidencePath) {
        $suiteEvidence = Get-Content -LiteralPath $SuiteEvidencePath -Raw -Encoding UTF8 | ConvertFrom-Json
        $Evidence["suite_passed"] = [int]$suiteEvidence.passed
        $Evidence["suite_failed"] = [int]$suiteEvidence.failed
        $Evidence["suite_failures"] = @($suiteEvidence.results | Where-Object { $_.status -ne "pass" } | ForEach-Object { [ordered]@{ name = $_.name; detail = $_.detail } })
        foreach ($item in $Evidence["suite_failures"]) { Add-Failure ("suite case " + $item.name + ": " + (($item.detail -split "`n")[0])) }
        Assert-True ($suiteRun.exit_code -eq 0 -and [int]$suiteEvidence.failed -eq 0) ("component suite: " + $suiteEvidence.passed + " passed, " + $suiteEvidence.failed + " failed")
    }
    else {
        Add-Failure "suite evidence file was not written (exit $($suiteRun.exit_code)); see suite-stderr.txt"
    }
}
else {
    Add-Failure "suite executable missing; component tests not run"
}

# ---------------------------------------------------------------------------
# Finite self-Job child scenarios (real processes, exact identity reaped)
# ---------------------------------------------------------------------------
$Evidence["selfjob_children"] = @()
$Evidence["selfjob_status"] = $(if ($SkipSelfJobChildren) { "not_run_explicitly_skipped" } else { "requested" })
if (-not $SkipSelfJobChildren -and (Test-Path -LiteralPath $SuiteExe)) {
    $scenarios = @(
        @{ name = "expire"; args = @("selfjob-child", "expire", [string]$SelfJobExpirySeconds); expect_exit = 124; timeout = ($SelfJobExpirySeconds + 30) },
        @{ name = "normal"; args = @("selfjob-child", "normal"); expect_exit = 0; timeout = 60 },
        @{ name = "second-enter"; args = @("selfjob-child", "second-enter"); expect_exit = 0; timeout = 60 },
        @{ name = "invalid"; args = @("selfjob-child", "invalid"); expect_exit = 0; timeout = 60 }
    )
    foreach ($scenario in $scenarios) {
        Write-Host "self-Job child scenario: $($scenario.name)"
        $run = Invoke-Native -FilePath $SuiteExe -Arguments $scenario.args -TimeoutSeconds $scenario.timeout
        $announce = $null
        foreach ($line in ($run.stdout -split "`n")) {
            if ($line.StartsWith("M6-CHILD ")) { $announce = ($line.Substring(9).Trim() | ConvertFrom-Json) }
        }
        $record = [ordered]@{
            scenario = $scenario.name; pid = $run.pid; creation_filetime_100ns = $run.creation_filetime_100ns
            active_job_processes = $run.active_job_processes; total_job_processes = $run.total_job_processes; cleanup_failure = $run.cleanup_failure; forced_termination = $run.forced_termination
            exit_code = $run.exit_code; expected_exit_code = $scenario.expect_exit; elapsed_ms = $run.elapsed_ms
            timed_out = $run.timed_out; exact_process_exited = $run.exact_process_exited
            announced = $announce; stderr = $run.stderr
        }
        $Evidence["selfjob_children"] += $record
        Assert-True (-not $run.timed_out) "self-Job child $($scenario.name) did not hang"
        Assert-True ($run.exit_code -eq $scenario.expect_exit) "self-Job child $($scenario.name) exit code $($run.exit_code) (expected $($scenario.expect_exit))"
        Assert-True ($run.exact_process_exited) "self-Job child $($scenario.name) exact PID/creation identity exited"
        if ($scenario.name -ne "invalid") {
            Assert-True ($null -ne $announce -and [int64]$announce.pid -eq $run.pid -and [int64]$announce.creation_filetime_100ns -eq $run.creation_filetime_100ns) "self-Job child $($scenario.name) announced the exact PID/creation time the parent holds"
        }
        if ($scenario.name -eq "expire") {
            $lower = $SelfJobExpirySeconds * 1000
            Assert-True ($run.elapsed_ms -ge $lower -and $run.elapsed_ms -le ($lower + 15000)) "watchdog terminated at the finite deadline (elapsed $($run.elapsed_ms) ms, deadline $lower ms)"
        }
        if ($scenario.name -eq "normal" -and $null -ne $announce) {
            Assert-True ([string]$announce.detail -match '^CHILD_(START_REFUSED:\d+|ACCOUNTED)$') "finite Job forbids or accounts a child process: $($announce.detail)"
        }
    }
}

# ---------------------------------------------------------------------------
# Evidence and exit
# ---------------------------------------------------------------------------
$Evidence["finished_utc"] = (Get-Date).ToUniversalTime().ToString("o")
$Evidence["failures"] = @($Failures)
$Evidence["failure_count"] = $Failures.Count
$EvidencePath = Join-Path $OutputRoot "runner-evidence.json"
Write-Utf8 -Path $EvidencePath -Text (($Evidence | ConvertTo-Json -Depth 12) + "`n")
Write-Host ""
Write-Host "evidence: $EvidencePath"
Write-Host "output root retained: $OutputRoot"
if ($Failures.Count -gt 0) {
    Write-Host "FAILED ($($Failures.Count)):" -ForegroundColor Red
    $Failures | ForEach-Object { Write-Host " - $_" }
    exit 1
}
if ($SkipSelfJobChildren) { Write-Host "PASSED component checks; self-Job children NOT RUN by explicit switch." }
else { $Evidence["selfjob_status"] = "passed"; Write-Utf8 -Path $EvidencePath -Text (($Evidence | ConvertTo-Json -Depth 12) + "`n"); Write-Host "PASSED component suite and actual self-Job children. No M6/G2/hour acceptance." }
exit 0
