"""Independent regression checks for the actual generated serving evidence helper."""

from __future__ import annotations
import ast
from concurrent.futures import ThreadPoolExecutor
from contextlib import contextmanager, redirect_stderr
import gc
import hashlib
import importlib.util
import io
import json
import os
from pathlib import Path
import sys
import tempfile
from types import ModuleType, SimpleNamespace
import unittest
from unittest.mock import Mock, mock_open, patch
import weakref
from tests._mineru_model_identity_fixture import (
    MetadataTensor,
    NeverInspect,
    hybrid,
    orientation,
)

SERVICE = Path(
    os.environ.get("MINERU_TEST_SERVICE_ROOT", Path(__file__).resolve().parents[2])
)
TEMP_ROOT = os.environ.get("MINERU_TEST_TEMP_ROOT")
PATCHER = SERVICE / "scripts/windows/mineru_heap_trim_compat/patch_mineru_344.py"
PREFIX = "MINERU_MODEL_DEVICE "


class ActualServingWrapper:
    pass


def weak_wrapper(value):
    out = ActualServingWrapper()
    out.__dict__.update(vars(value))
    return out


class ModelIdentityTests(unittest.TestCase):
    def setUp(self):
        self.env = patch.dict(
            os.environ,
            {
                "MINERU_PHASE_TRACE": "1",
                "MINERU_DEVICE_MODE": "cuda:0",
                "MINERU_CAPACITY_CONFIG_SHA256": "sha256:" + "a" * 64,
            },
            clear=True,
        )
        self.env.start()
        spec = importlib.util.spec_from_file_location(
            "independent_actual_patcher", PATCHER
        )
        self.patcher = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(self.patcher)
        # Compile the exact helper generated by production patch_source. Avoid all
        # torch/MinerU imports and process/bootstrap startup in the no-DB test.
        small = "import math\nimport os\nimport time\nimport gc\n\ndef clean_memory(device='cuda'):\n    gc.collect()\n"
        patched = self.patcher.patch_source("mineru/utils/model_utils.py", small)
        self.ns = {}
        with patch.dict(os.environ, {"MINERU_PHASE_TRACE": "1"}, clear=True):
            exec(compile(patched, "actual-patched-model-utils.py", "exec"), self.ns)
        self.record = self.ns["record_hybrid_model_devices"]
        self.bootstrap = ModuleType("mineru.cli.agent_capacity_bootstrap")
        self.bootstrap.get_process_capacity = Mock(
            return_value=SimpleNamespace(sha256="sha256:" + "a" * 64)
        )
        self.module_patch = patch.dict(
            sys.modules,
            {
                "mineru": ModuleType("mineru"),
                "mineru.cli": ModuleType("mineru.cli"),
                "mineru.cli.agent_capacity_bootstrap": self.bootstrap,
            },
        )
        self.module_patch.start()
        # No actual Linux /proc dependency, subprocess, model, network or service.
        stat = "314 (name with ) parentheses) " + " ".join(
            ["S"] + ["0"] * 18 + ["987654"] + ["0"] * 3
        )
        self.proc = patch("builtins.open", mock_open(read_data=stat))
        self.proc.start()
        self.output = io.StringIO()
        self.redirect = redirect_stderr(self.output)
        self.redirect.__enter__()

    def tearDown(self):
        self.redirect.__exit__(None, None, None)
        self.proc.stop()
        self.module_patch.stop()
        self.env.stop()

    def events(self):
        lines = self.output.getvalue().splitlines()
        self.assertTrue(all(x.startswith(PREFIX) for x in lines))
        return [json.loads(x[len(PREFIX) :]) for x in lines]

    @contextmanager
    def real_bootstrap(self):
        # Existing independent fixture copies all actual codec/reader/bootstrap bytes.
        # Local scratch config only; no GPU/service/production capacity configuration.
        spec = importlib.util.spec_from_file_location(
            "independent_bootstrap_fixture",
            SERVICE / "tests/_mineru_capacity_bootstrap_fixture.py",
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        with tempfile.TemporaryDirectory(
            prefix="independent-serving-capacity-", dir=TEMP_ROOT
        ) as temporary:
            temporary = str(Path(temporary).resolve())
            fixture = module.CapacityBootstrapFixture(Path(temporary))
            try:
                payload = {
                    "api_event_loop_limit": 1,
                    "api_process_limit": 1,
                    "contract_version": "mineru.capacity-config.v1",
                    "final_http_limit_per_loop": 7,
                    "finalizer_active_limit": 1,
                    "hybrid_batch_ratio_requested": 1,
                    "max_unacked_result_bytes": 2097152,
                    "mkl_num_threads": 4,
                    "omp_num_threads": 4,
                    "openblas_num_threads": 1,
                    "parse_active_limit": 5,
                    "pdf_render_processes_requested": 3,
                    "pipeline_inference_locks": True,
                    "processing_window_size": 16,
                    "result_reservation_bytes": 262144,
                    "total_nonterminal_limit": 6,
                }
                raw = json.dumps(
                    payload, sort_keys=True, separators=(",", ":")
                ).encode()
                path = Path(temporary) / "capacity.json"
                path.write_bytes(raw)
                path.chmod(0o600)
                digest = "sha256:" + hashlib.sha256(raw).hexdigest()
                environment = {
                    "MINERU_CAPACITY_CONFIG_PATH": str(path),
                    "MINERU_CAPACITY_CONFIG_SHA256": digest,
                    "MINERU_API_MAX_CONCURRENT_REQUESTS": "5",
                    "MINERU_API_MAX_PENDING_TASKS": "6",
                    "MINERU_API_FINALIZER_SLOTS": "1",
                    "MINERU_PROCESSING_WINDOW_SIZE": "16",
                    "OMP_NUM_THREADS": "4",
                    "MKL_NUM_THREADS": "4",
                    "OPENBLAS_NUM_THREADS": "1",
                    "MINERU_PDF_RENDER_THREADS": "3",
                    "MINERU_HYBRID_BATCH_RATIO": "1",
                    "MINERU_ENABLE_PIPELINE_INFERENCE_LOCKS": "1",
                    "MINERU_TASK_PROTOCOL_V2_RESULT_RESERVATION_BYTES": "262144",
                    "MINERU_TASK_PROTOCOL_V2_MAX_UNACKED_BYTES": "2097152",
                    "MINERU_PHASE_TRACE": "1",
                    "MINERU_DEVICE_MODE": "cuda:0",
                }
                with patch.dict(os.environ, environment, clear=True):
                    yield fixture.bootstrap, digest
            finally:
                fixture.close()

    def test_no_capacity_anchors_does_not_call_bootstrap_and_reports_none(self):
        with patch.dict(os.environ, {"MINERU_PHASE_TRACE": "1"}, clear=True):
            event = self.record(weak_wrapper(hybrid()))
        self.assertIsNone(event["capacity_config_sha256"])
        self.bootstrap.get_process_capacity.assert_not_called()

    def test_identity_uses_verified_getter_result_not_environment_echo(self):
        self.bootstrap.get_process_capacity.return_value = SimpleNamespace(
            sha256="sha256:" + "b" * 64
        )
        event = self.record(weak_wrapper(hybrid()))
        self.assertEqual(
            os.environ["MINERU_CAPACITY_CONFIG_SHA256"], "sha256:" + "a" * 64
        )
        self.assertEqual(event["capacity_config_sha256"], "sha256:" + "b" * 64)
        self.bootstrap.get_process_capacity.assert_called_once_with()

    def test_actual_bootstrap_verifies_file_and_rejects_later_capacity_environment_drift(
        self,
    ):
        with self.real_bootstrap() as (bootstrap, digest):
            verified = bootstrap.get_process_capacity()
            self.assertEqual(verified.sha256, digest)
            with patch.object(
                bootstrap, "get_process_capacity", wraps=bootstrap.get_process_capacity
            ) as getter:
                event = self.record(weak_wrapper(hybrid()))
                self.assertEqual(event["capacity_config_sha256"], digest)
                getter.assert_called_once_with()
            for key, bad in [
                ("OMP_NUM_THREADS", "99"),
                ("MINERU_CAPACITY_CONFIG_SHA256", "sha256:" + "0" * 64),
                ("MINERU_CAPACITY_CONFIG_PATH", "/not-the-bound-file"),
            ]:
                with self.subTest(key=key), patch.dict(os.environ, {key: bad}):
                    count = len(self.events())
                    item = weak_wrapper(hybrid())
                    with self.assertRaisesRegex(RuntimeError, "drifted"):
                        self.record(item)
                    self.assertEqual(len(self.events()), count)
                # A rejected record does not mark the serving object as seen.
                self.assertIsNotNone(self.record(item))

    def test_either_partial_capacity_anchor_invokes_actual_bootstrap_and_rejects(self):
        for remove in ("MINERU_CAPACITY_CONFIG_PATH", "MINERU_CAPACITY_CONFIG_SHA256"):
            with (
                self.subTest(remove=remove),
                self.real_bootstrap() as (bootstrap, _digest),
            ):
                del os.environ[remove]
                with patch.object(
                    bootstrap,
                    "get_process_capacity",
                    wraps=bootstrap.get_process_capacity,
                ) as getter:
                    with self.assertRaisesRegex(
                        ValueError, "path and SHA must both be explicit"
                    ):
                        self.record(weak_wrapper(hybrid()))
                    getter.assert_called_once_with()
        self.assertEqual(self.events(), [])

    def test_disabled_does_not_touch_model_or_proc(self):
        with (
            patch.dict(os.environ, {"MINERU_PHASE_TRACE": "0"}),
            patch("builtins.open", side_effect=AssertionError("disabled read")),
        ):
            self.assertIsNone(self.record(NeverInspect()))
        self.assertEqual(self.events(), [])

    def test_actual_cpu_tensors_override_cuda_environment_and_wrapper_claim(self):
        item = weak_wrapper(hybrid("cpu"))
        event = self.record(item)
        self.assertEqual(event["schema"], "mineru-hybrid-model-device.v1")
        self.assertEqual(event["observation"], "serving_instance_initialization")
        self.assertEqual(event["process_start_ticks"], 987654)
        self.assertEqual(event["process_id"], os.getpid())
        self.assertEqual(event["capacity_config_sha256"], "sha256:" + "a" * 64)
        self.assertEqual(event["instance_id"], id(item))
        self.assertEqual(
            set(event["models"]), {"layout", "mfr", "ocr_detector", "ocr_recognizer"}
        )
        for model in event["models"].values():
            self.assertEqual(model["state"], "available")
            self.assertEqual({g["device"] for g in model["tensor_groups"]}, {"cpu"})
            self.assertEqual(
                {g["dtype"] for g in model["tensor_groups"]}, {"torch.float32"}
            )
        self.assertEqual(self.events(), [event])

    def test_all_tensor_groups_include_buffer_and_mixed_parameter_metadata(self):
        item = weak_wrapper(hybrid())
        item.layout_model.model._parameters.append(
            MetadataTensor("cuda:1", "torch.float64", (4,))
        )
        item.layout_model.model._buffers = [
            MetadataTensor("cpu", "torch.int64", (1,)),
            MetadataTensor("cuda:0", "torch.float32", (2,)),
        ]
        event = self.record(item)
        groups = event["models"]["layout"]["tensor_groups"]
        self.assertEqual(
            {(g["kind"], g["device"], g["dtype"], g["elements"]) for g in groups},
            {
                ("parameters", "cuda:0", "torch.float32", 6),
                ("parameters", "cuda:1", "torch.float64", 4),
                ("buffers", "cpu", "torch.int64", 1),
                ("buffers", "cuda:0", "torch.float32", 2),
            },
        )
        self.assertEqual(
            event["models"]["mfr"]["tensor_groups"][0]["dtype"], "torch.float16"
        )
        self.assertEqual(
            event["models"]["ocr_detector"]["tensor_groups"][0]["dtype"],
            "torch.float16",
        )
        self.assertEqual(
            event["models"]["layout"]["weight_path"],
            "/weights/snapshots/revision/layout",
        )
        self.assertEqual(
            event["models"]["mfr"]["weight_path"], "/weights/snapshots/revision/mfr"
        )

    def test_orientation_uses_actual_orientation_ocr_not_hybrid_ocr(self):
        item = weak_wrapper(orientation())
        event = self.record(item, role="orientation")
        self.assertEqual(set(event["models"]), {"ocr_detector", "ocr_recognizer"})
        self.assertEqual(
            event["models"]["ocr_detector"]["weight_path"],
            "/weights/snapshots/revision/orientation/det.safetensors",
        )
        self.assertEqual(
            event["models"]["ocr_recognizer"]["weight_path"],
            "/weights/snapshots/revision/orientation/rec.safetensors",
        )

    def test_missing_weights_and_empty_models_are_not_available(self):
        item = weak_wrapper(hybrid())
        del item.layout_model.model_dir
        item.mfr_model.model._parameters = []
        item.ocr_model.text_detector.net = None
        event = self.record(item)
        for name in ("layout", "mfr", "ocr_detector"):
            self.assertEqual(event["models"][name]["state"], "unavailable")
        self.assertIsNone(event["models"]["layout"]["weight_path"])
        self.assertEqual(event["models"]["mfr"]["tensor_groups"], [])
        self.assertEqual(event["models"]["ocr_recognizer"]["state"], "available")

    def test_concurrent_same_instance_only_once_distinct_instances_survive(self):
        item = weak_wrapper(hybrid())
        with ThreadPoolExecutor(max_workers=6) as executor:
            values = list(executor.map(lambda _: self.record(item), range(18)))
        self.assertEqual(sum(v is not None for v in values), 1)
        self.assertEqual(len(self.events()), 1)
        other = weak_wrapper(hybrid())
        self.assertIsNotNone(self.record(other))
        self.assertEqual(len(self.events()), 2)

    def test_instances_not_retained_by_dedup_registry(self):
        item = weak_wrapper(hybrid())
        self.record(item)
        ref = weakref.ref(item)
        del item
        gc.collect()
        self.assertIsNone(ref())

    def test_unknown_role_rejected_without_emitting(self):
        with self.assertRaises(ValueError):
            self.record(weak_wrapper(hybrid()), role="typo")
        self.assertEqual(self.events(), [])

    def test_unexpected_metadata_failure_visible_and_retry_not_suppressed(self):
        item = weak_wrapper(hybrid())
        original = item.layout_model.model.parameters
        item.layout_model.model.parameters = lambda: (_ for _ in ()).throw(
            RuntimeError("metadata getter failure")
        )
        with self.assertRaisesRegex(RuntimeError, "metadata getter failure"):
            self.record(item)
        self.assertEqual(self.events(), [])
        item.layout_model.model.parameters = original
        self.assertIsNotNone(self.record(item))

    def test_pinned_real_sources_compile_and_hooks_follow_actual_getters(self):
        root = SERVICE / "tests/fixtures/mineru_344_preimages"
        for rel, expected in self.patcher.TARGET_PREIMAGE_SHA256.items():
            with self.subTest(path=rel):
                raw = (root / rel).read_bytes()
                self.assertEqual(hashlib.sha256(raw).hexdigest(), expected)
                patched = self.patcher.patch_source(rel, raw.decode())
                compile(patched, rel, "exec")
                if rel == "mineru/backend/hybrid/hybrid_analyze.py":
                    tree = ast.parse(patched)
                    funcs = {
                        n.name: n
                        for n in tree.body
                        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
                    }
                    func = funcs["_predict_layout_for_window"]
                    statements = func.body
                    get_index = next(
                        i
                        for i, n in enumerate(statements)
                        if isinstance(n, ast.Assign)
                        and any(
                            isinstance(t, ast.Name) and t.id == "hybrid_pipeline_model"
                            for t in n.targets
                        )
                    )
                    record = statements[get_index + 1]
                    self.assertIsInstance(record, ast.Expr)
                    self.assertEqual(
                        record.value.func.id, "record_hybrid_model_devices"
                    )
                    self.assertEqual(record.value.args[0].id, "hybrid_pipeline_model")
                    orient = funcs["_apply_medium_table_orientation_labels"]
                    body = ast.unparse(orient)
                    self.assertLess(
                        body.index("get_atom_model("),
                        body.index("record_hybrid_model_devices("),
                    )
                    self.assertLess(
                        body.index("record_hybrid_model_devices("),
                        body.index("run_ocr_inference("),
                    )


if __name__ == "__main__":
    unittest.main(verbosity=2)
