include_tables:
  - "ai_is.quantitative_alternative_high_frequency_signals"
  - "ai_is.quantitative_alternative_institutional_patent_signals"
  - "ai_is.quantitative_analyst_coverage_rating_signals"
  - "ai_is.quantitative_analyst_earnings_revision_signals"
  - "ai_is.quantitative_growth_forecast_trend_signals"
  - "ai_is.quantitative_growth_profitability_signals"
  - "ai_is.quantitative_growth_revenue_asset_signals"
  - "ai_is.quantitative_other_signals"
  - "ai_is.quantitative_quality_cashflow_safety_signals"
  - "ai_is.quantitative_quality_operating_efficiency_signals"
  - "ai_is.quantitative_quality_profit_quality_signals"
  - "ai_is.quantitative_sentiment_liquidity_signals"
  - "ai_is.quantitative_sentiment_momentum_signals"
  - "ai_is.quantitative_sentiment_price_return_signals"
  - "ai_is.quantitative_sentiment_value_reversal_signals"
  - "ai_is.quantitative_sentiment_volatility_signals"
  - "ai_is.quantitative_value_valuation_signals"
