"""Repository ports.

Repositories persist and load domain entities. Concrete implementations live in
``adapters/db/postgres``. Use cases depend only on these protocols.
"""

from __future__ import annotations

from typing import Optional, Protocol

from disclosure_anchor.domain.entities import (
    Company,
    CompanyIdentifier,
    Document,
    DocumentUnit,
    OutboxEvent,
    ProcessingRun,
    Security,
    SourceAccess,
    SourceCheckpoint,
    TrackedCompany,
)


class CompanyRepository(Protocol):
    def add(self, company: Company) -> Company: ...
    def get(self, company_id: str) -> Optional[Company]: ...
    def get_by_legal_name(self, legal_name: str) -> Optional[Company]: ...
    def get_by_credit_code(self, uscc: str) -> Optional[Company]: ...
    def update(self, company: Company) -> Company: ...


class CompanyIdentifierRepository(Protocol):
    def add(self, identifier: CompanyIdentifier) -> CompanyIdentifier: ...
    def get(self, identifier_id: str) -> Optional[CompanyIdentifier]: ...
    def get_by_scheme_value(
        self, scheme: str, normalized_value: str
    ) -> Optional[CompanyIdentifier]: ...
    def update(self, identifier: CompanyIdentifier) -> CompanyIdentifier: ...


class SecurityRepository(Protocol):
    def add(self, security: Security) -> Security: ...
    def get(self, security_id: str) -> Optional[Security]: ...
    def get_by_code_exchange(self, security_code: str, exchange: str) -> Optional[Security]: ...


class TrackedCompanyRepository(Protocol):
    def add(self, tracked_company: TrackedCompany) -> TrackedCompany: ...
    def get(self, tracked_company_id: str) -> Optional[TrackedCompany]: ...


class SourceAccessRepository(Protocol):
    def add(self, source_access: SourceAccess) -> SourceAccess: ...
    def get(self, source_access_id: str) -> Optional[SourceAccess]: ...


class SourceCheckpointRepository(Protocol):
    def add(self, checkpoint: SourceCheckpoint) -> SourceCheckpoint: ...
    def get(self, source_checkpoint_id: str) -> Optional[SourceCheckpoint]: ...


class DocumentRepository(Protocol):
    def add(self, document: Document) -> Document: ...
    def get(self, document_id: str) -> Optional[Document]: ...
    def get_for_update(self, document_id: str) -> Optional[Document]: ...
    def update(self, document: Document) -> Document: ...
    def get_by_provider_document_and_hash(
        self, *, provider: str, provider_document_id: str, raw_file_hash: str
    ) -> Optional[Document]: ...
    def latest_by_provider_document(
        self, *, provider: str, provider_document_id: str
    ) -> Optional[Document]: ...


class ProcessingRunRepository(Protocol):
    def add(self, run: ProcessingRun) -> ProcessingRun: ...
    def get(self, processing_run_id: str) -> Optional[ProcessingRun]: ...
    def latest_succeeded_parse_for_document(
        self, document_id: str
    ) -> Optional[ProcessingRun]: ...
    def update(self, run: ProcessingRun) -> ProcessingRun: ...


class DocumentUnitRepository(Protocol):
    def add(self, unit: DocumentUnit) -> DocumentUnit: ...
    def add_many(self, units: list[DocumentUnit]) -> list[DocumentUnit]: ...
    def get(self, asset_id: str) -> Optional[DocumentUnit]: ...
    def list_by_processing_run(self, processing_run_id: str) -> list[DocumentUnit]: ...
    def list_by_document_active(self, document_id: str) -> list[DocumentUnit]: ...


class OutboxRepository(Protocol):
    def add(self, event: OutboxEvent) -> OutboxEvent: ...
    def get(self, event_id: str) -> Optional[OutboxEvent]: ...
