"""Pure release projection: capacity + deployment profile -> complete Compose.

No network, Docker, database or filesystem access. The Compose document is a
structured object rendered by a deterministic emitter and re-parsed for
verification; the only capacity numbers it contains come from the shared
codec projection. Nothing here reads a previous package.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from typing import Any

import yaml

from disclosure_anchor.application.contracts.mineru_capacity_config import (
    MineruCapacityConfig,
    capacity_environment,
    capacity_http_arguments,
    encode_mineru_capacity_config,
)
from disclosure_anchor.application.contracts.mineru_deployment_profile import MineruDeploymentProfile
from disclosure_anchor.application.contracts.mineru_local_worker_profile import MineruLocalWorkerProfile


CURRENT_RUNTIME_PROCESSING_WINDOW_SIZE = 16
API_FIXED_ARGV = ("--host", "0.0.0.0", "--port", "8000", "--allow-public-http-client")
API_CONTAINER_OUTPUT_ROOT = "/var/lib/mineru-api-output"
API_STOP_GRACE_SECONDS = 10
PROXY_PROGRAM = (
    "import asyncio\n"
    "\n"
    "async def copy_stream(source, destination):\n"
    "    try:\n"
    "        while data := await source.read(65536):\n"
    "            destination.write(data)\n"
    "            await destination.drain()\n"
    "    finally:\n"
    "        try:\n"
    "            destination.write_eof()\n"
    "        except (AttributeError, OSError):\n"
    "            pass\n"
    "\n"
    "async def proxy(client_reader, client_writer):\n"
    "    upstream_reader, upstream_writer = await asyncio.open_connection(\"mineru-api\", 8000)\n"
    "    try:\n"
    "        await asyncio.gather(\n"
    "            copy_stream(client_reader, upstream_writer),\n"
    "            copy_stream(upstream_reader, client_writer),\n"
    "        )\n"
    "    finally:\n"
    "        upstream_writer.close()\n"
    "        client_writer.close()\n"
    "        await asyncio.gather(\n"
    "            upstream_writer.wait_closed(),\n"
    "            client_writer.wait_closed(),\n"
    "            return_exceptions=True,\n"
    "        )\n"
    "\n"
    "async def main():\n"
    "    server = await asyncio.start_server(proxy, \"0.0.0.0\", 8000)\n"
    "    async with server:\n"
    "        await server.serve_forever()\n"
    "\n"
    "asyncio.run(main())\n"
)
_PLAIN_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*$")
COMPOSE_HEADER = (
    "# Generated by disclosure_anchor.cli.mineru_release build; do not edit.\n"
    "# Capacity values are projected from the canonical capacity config; the\n"
    "# release manifest binds this file by hash.\n"
)


@dataclass(frozen=True, slots=True)
class ReleasePlan:
    api_environment: dict[str, str]
    api_command: tuple[str, ...]
    compose_document: dict[str, Any]
    compose_bytes: bytes
    local_profile_admits_full_pending: bool


def require_current_runtime_capabilities(capacity: MineruCapacityConfig) -> None:
    """Reject capacity requests the current patched runtime cannot honour.

    The codec admits a wider envelope than the deployed patch set supports:
    window size is fixed by the current native patch, and one process/loop is
    the only qualified topology.
    """

    encode_mineru_capacity_config(capacity)
    if capacity.processing_window_size != CURRENT_RUNTIME_PROCESSING_WINDOW_SIZE:
        raise ValueError(
            f"current runtime supports processing_window_size {CURRENT_RUNTIME_PROCESSING_WINDOW_SIZE} only"
        )
    if capacity.api_process_limit != 1 or capacity.api_event_loop_limit != 1:
        raise ValueError("current runtime supports one API process and one event loop only")


def api_command_argv(capacity: MineruCapacityConfig) -> tuple[str, ...]:
    return API_FIXED_ARGV + capacity_http_arguments(capacity)


def compose_document(profile: MineruDeploymentProfile, capacity: MineruCapacityConfig) -> dict[str, Any]:
    """Structured Compose with every capacity consumer projected once."""

    profile.__post_init__()
    environment: dict[str, Any] = {
        "MINERU_MODEL_SOURCE": "local",
    }
    if profile.api_device_profile == "cuda0":
        environment["MINERU_DEVICE_MODE"] = profile.api_device_mode
    environment["MINERU_MALLOC_TRIM"] = "1"
    environment["MINERU_PHASE_TRACE"] = "1" if profile.api_phase_trace else "0"
    environment.update(capacity_environment(capacity))
    environment.update({
        "MINERU_API_OUTPUT_ROOT": API_CONTAINER_OUTPUT_ROOT,
        "MINERU_API_TASK_RETENTION_SECONDS": str(profile.api_task_retention_seconds),
        "MINERU_API_TASK_CLEANUP_INTERVAL_SECONDS": str(profile.api_task_cleanup_interval_seconds),
        "MINERU_API_DISABLE_ACCESS_LOG": "true",
        "MINERU_API_ENABLE_FASTAPI_DOCS": "false",
    })
    api: dict[str, Any] = {
        "image": profile.api_image_reference,
        "pull_policy": "never",
        "container_name": "mineru-api",
        "stop_grace_period": f"{API_STOP_GRACE_SECONDS}s",
        "restart": "always",
    }
    if profile.api_memory_limit_bytes is not None:
        api["mem_limit"] = profile.api_memory_limit_bytes
        api["memswap_limit"] = profile.api_memory_limit_bytes
    api.update({
        "environment": environment,
        "entrypoint": ["mineru-api"],
        "command": list(api_command_argv(capacity)),
        "volumes": [{
            "type": "bind",
            "source": profile.api_output_root_windows,
            "target": API_CONTAINER_OUTPUT_ROOT,
        }],
    })
    if profile.api_device_profile == "cuda0":
        api["deploy"] = {"resources": {"reservations": {"devices": [
            {"driver": "nvidia", "device_ids": ["0"], "capabilities": ["gpu"]},
        ]}}}
    api.update({
        "depends_on": {"mineru-openai-server": {"condition": "service_healthy"}},
        "healthcheck": {
            "test": [
                "CMD-SHELL",
                "/usr/bin/python3.12 -I -c 'import json,urllib.request; "
                "value=json.load(urllib.request.urlopen(\"http://127.0.0.1:8000/health\",timeout=3)); "
                "assert value.get(\"task_protocol_schema\")==\"mineru-task-protocol.v2\"'",
            ],
            "interval": "15s", "timeout": "5s", "retries": 12, "start_period": "30s", "start_interval": "3s",
        },
        "networks": ["inference"],
    })
    inference: dict[str, Any] = {
        "image": profile.base_image_repo_digest,
        "pull_policy": "never",
        "container_name": "mineru-openai-server",
        "restart": "always",
        "environment": {"MINERU_MODEL_SOURCE": "local"},
        "entrypoint": ["mineru-openai-server"],
        "command": [
            "--host", "0.0.0.0", "--port", "30000",
            "--max-num-seqs", str(profile.inference_max_num_seqs),
            "--mm-processor-cache-gb", str(profile.inference_mm_processor_cache_gb),
        ],
        "ports": [{
            "name": "vllm-observability", "target": 30000, "host_ip": "127.0.0.1",
            "published": str(profile.vllm_observability_published_port), "protocol": "tcp",
        }],
        "ipc": "host",
        "security_opt": ["label=disable"],
        "ulimits": {"memlock": -1, "stack": 67108864},
        "deploy": {"resources": {"reservations": {"devices": [
            {"driver": "nvidia", "device_ids": ["0"], "capabilities": ["gpu"]},
        ]}}},
        "healthcheck": {
            "test": ["CMD-SHELL", "curl --fail --silent --show-error http://127.0.0.1:30000/health >/dev/null"],
            "interval": "30s", "timeout": "10s", "retries": 20, "start_period": "300s", "start_interval": "5s",
        },
        "networks": ["runtime", "inference"],
    }
    proxy: dict[str, Any] = {
        "image": profile.base_image_repo_digest,
        "pull_policy": "never",
        "container_name": "mineru-api-proxy",
        "restart": "always",
        "entrypoint": ["/usr/bin/python3.12"],
        "command": ["-I", "-c", PROXY_PROGRAM],
        "ports": [{
            "name": "mineru-api", "target": 8000, "host_ip": "127.0.0.1",
            "published": str(profile.api_published_port), "protocol": "tcp",
        }],
        "depends_on": {"mineru-api": {"condition": "service_healthy"}},
        "healthcheck": {
            "test": ["CMD-SHELL", "curl --fail --silent --show-error http://127.0.0.1:8000/health >/dev/null"],
            "interval": "15s", "timeout": "5s", "retries": 12, "start_period": "15s", "start_interval": "3s",
        },
        "read_only": True,
        "tmpfs": ["/tmp:size=16m,mode=1777"],
        "cap_drop": ["ALL"],
        "security_opt": ["no-new-privileges=true", "label=disable"],
        "networks": ["inference", "runtime"],
    }
    return {
        "name": profile.project_name,
        "services": {
            "mineru-openai-server": inference,
            "mineru-api": api,
            "mineru-api-proxy": proxy,
        },
        "networks": {
            "runtime": {"driver": "bridge"},
            "inference": {"driver": "bridge", "internal": True},
        },
    }


def _scalar(value: object) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if type(value) is int:
        return str(value)
    if type(value) is str:
        if "\n" in value:
            raise ValueError("multi-line strings must be emitted as literal blocks")
        return json.dumps(value, ensure_ascii=False)
    raise ValueError(f"unsupported Compose scalar type: {type(value).__name__}")


def _key(value: object) -> str:
    if type(value) is not str or not value:
        raise ValueError("Compose mapping keys must be non-empty strings")
    return value if _PLAIN_KEY_RE.fullmatch(value) else json.dumps(value, ensure_ascii=False)


def _emit(value: object, indent: int, lines: list[str]) -> None:
    pad = " " * indent
    if type(value) is dict:
        if not value:
            raise ValueError("empty Compose mappings are not emitted")
        for key, item in value.items():
            if type(item) is dict and item:
                lines.append(f"{pad}{_key(key)}:")
                _emit(item, indent + 2, lines)
            elif type(item) is list and item:
                lines.append(f"{pad}{_key(key)}:")
                _emit(item, indent + 2, lines)
            elif type(item) is str and "\n" in item:
                lines.append(f"{pad}{_key(key)}: |")
                _emit_block(item, indent + 2, lines)
            else:
                lines.append(f"{pad}{_key(key)}: {_scalar(item)}")
        return
    if type(value) is list:
        if not value:
            raise ValueError("empty Compose lists are not emitted")
        for item in value:
            if type(item) is dict and item:
                first = True
                for key, nested in item.items():
                    prefix = f"{pad}- " if first else f"{pad}  "
                    first = False
                    if type(nested) is dict and nested:
                        lines.append(f"{prefix}{_key(key)}:")
                        _emit(nested, indent + 4, lines)
                    elif type(nested) is list and nested:
                        lines.append(f"{prefix}{_key(key)}:")
                        _emit(nested, indent + 4, lines)
                    elif type(nested) is str and "\n" in nested:
                        lines.append(f"{prefix}{_key(key)}: |")
                        _emit_block(nested, indent + 4, lines)
                    else:
                        lines.append(f"{prefix}{_key(key)}: {_scalar(nested)}")
            elif type(item) is list:
                raise ValueError("nested Compose lists are not emitted")
            elif type(item) is str and "\n" in item:
                lines.append(f"{pad}- |")
                _emit_block(item, indent + 2, lines)
            else:
                lines.append(f"{pad}- {_scalar(item)}")
        return
    raise ValueError("Compose root must be a mapping")


def _emit_block(text: str, indent: int, lines: list[str]) -> None:
    if not text.endswith("\n") or text.count("\n") != len(text.split("\n")) - 1 or "\r" in text:
        raise ValueError("literal block text must end with one newline and contain no carriage returns")
    body = text[:-1].split("\n")
    if body[0] and body[0][0] in " \t":
        raise ValueError("literal block must not start with indentation")
    if any(line != line.rstrip() for line in body):
        raise ValueError("literal block lines must not carry trailing whitespace")
    pad = " " * indent
    for line in body:
        lines.append(f"{pad}{line}" if line else "")


def render_compose_yaml(document: dict[str, Any]) -> bytes:
    lines: list[str] = []
    _emit(document, 0, lines)
    return (COMPOSE_HEADER + "\n".join(lines) + "\n").encode("utf-8")


class _UniqueKeyLoader(yaml.SafeLoader):
    pass


def _construct_unique_mapping(loader: yaml.SafeLoader, node: yaml.MappingNode) -> dict[Any, Any]:
    mapping: dict[Any, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=True)
        if key in mapping:
            raise ValueError(f"duplicate Compose key: {key!r}")
        mapping[key] = loader.construct_object(value_node, deep=True)
    return mapping


_UniqueKeyLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _construct_unique_mapping)


def parse_compose_yaml(payload: bytes) -> dict[str, Any]:
    if type(payload) is not bytes or not payload or len(payload) > 256 * 1024:
        raise ValueError("Compose bytes are outside the closed envelope")
    try:
        value = yaml.load(payload.decode("utf-8"), Loader=_UniqueKeyLoader)  # noqa: S506 - SafeLoader subclass
    except (UnicodeDecodeError, yaml.YAMLError) as exc:
        raise ValueError(f"Compose is not parseable YAML: {exc}") from exc
    if type(value) is not dict:
        raise ValueError("Compose root must be a mapping")
    return value


def verify_compose_projection(
    document: dict[str, Any], capacity: MineruCapacityConfig, profile: MineruDeploymentProfile,
) -> list[str]:
    """Return every mismatch between a parsed Compose and the exact projection."""

    mismatches: list[str] = []
    expected = compose_document(profile, capacity)
    if document != expected:
        api = document.get("services", {}).get("mineru-api") if type(document.get("services")) is dict else None
        environment = api.get("environment") if type(api) is dict else None
        if type(environment) is not dict:
            mismatches.append("services.mineru-api.environment: missing")
        else:
            for name, value in capacity_environment(capacity).items():
                if environment.get(name) != value:
                    mismatches.append(f"services.mineru-api.environment.{name}: {environment.get(name)!r} != {value!r}")
            for name in ("MINERU_CAPACITY_CONFIG_PATH", "MINERU_CAPACITY_CONFIG_SHA256"):
                if name in environment:
                    mismatches.append(f"services.mineru-api.environment.{name}: compose must not override the image anchor")
            extra = set(environment) - set(expected["services"]["mineru-api"]["environment"])
            for name in sorted(extra):
                mismatches.append(f"services.mineru-api.environment.{name}: undeclared variable")
        command = api.get("command") if type(api) is dict else None
        if command != list(api_command_argv(capacity)):
            mismatches.append(f"services.mineru-api.command: {command!r} != {list(api_command_argv(capacity))!r}")
        if not mismatches:
            mismatches.append("compose document differs from the exact projection outside capacity fields")
    return mismatches


def resolve_release(
    capacity: MineruCapacityConfig,
    deployment_profile: MineruDeploymentProfile,
    local_profile: MineruLocalWorkerProfile,
) -> ReleasePlan:
    """Project all inputs once; pure and deterministic."""

    require_current_runtime_capabilities(capacity)
    deployment_profile.__post_init__()
    local_profile.__post_init__()
    document = compose_document(deployment_profile, capacity)
    rendered = render_compose_yaml(document)
    if parse_compose_yaml(rendered) != document:
        raise ValueError("rendered Compose does not round-trip to its structured document")
    # The Mac process-profile contract requires every admitted pending task to
    # hold a full reservation within the retained-result budget; the API
    # registry itself only backpressures. Report the difference; never hide it.
    admits_full_pending = (
        capacity.result_reservation_bytes * capacity.total_nonterminal_limit <= capacity.max_unacked_result_bytes
    )
    return ReleasePlan(
        api_environment=capacity_environment(capacity),
        api_command=api_command_argv(capacity),
        compose_document=document,
        compose_bytes=rendered,
        local_profile_admits_full_pending=admits_full_pending,
    )


__all__ = [
    "API_FIXED_ARGV",
    "CURRENT_RUNTIME_PROCESSING_WINDOW_SIZE",
    "PROXY_PROGRAM",
    "ReleasePlan",
    "api_command_argv",
    "compose_document",
    "parse_compose_yaml",
    "render_compose_yaml",
    "require_current_runtime_capabilities",
    "resolve_release",
    "verify_compose_projection",
]
